services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - ./data/chroma_data:/chroma/.chroma/index
    networks:
      - rag-network

  backend:
    build: 
      context: ./backend
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - chromadb
    networks:
      - rag-network

  frontend:
    build: 
      context: ../frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge
